pipeline{
    agent{
        docker{
            image 'custom-jenkins-agent'
            args '-v /var/run/docker.sock:/var/run/docker.sock -u root'
        }
    }
    stages{
        stage('build stage'){
            steps{
                sh 'docker compose -f deploy/docker-compose.yml up -d --build'
                sleep 5
            }
        }
        stage('Test'){
            steps{
                sh 'docker compose -f deploy/docker-compose.yml exec -T webapp wget -q0- http://127.0.0.0:5000/health'
            }
        }
    }
    post{
        always{
            sh 'docker compose -f deploy/docker-compose.yml down'
        }
    }
}